### ISSUE TITLE
how to handle re-balancing error?

### ISSUE THREAD

**Issue by dczielinski** [opencobra/MASSef#59]
For many enzymes we're not going to get a perfect fit -  we need more flexibility in controlling where the error ends up. Some options

1) the relative vs absolute objective criteria being used as an extra LMA step would rebalance more equally among Kms and kcats
2) Allowing flexibility in the number of data points simulated for each parameter would allow us to weight certain parameters more heavily so they fit more precisely (and vice versa) - this is very general but also a bit crude in implementation (but we currently do it for kcats already, and print out an arbitrary number of points for the Km curves as well)
3) we could also put arbitrary weightings directly in the objective for each parameter. this is more elegant than 2 but a bit more involved in implementation. ideally the user could control the weights as an input somewhere. if we have an automatic weight based on the value, this becomes the same as a relative ssd objective function, basically

option 3 would be best, just need to think about specific implementations. option 2 would be quick and dirty as a stopgap implementation

**Comment by martamatos** [comment]
i think with the LMA objective function fixed and the weights, this is pretty much solved

**Comment by dczielinski** [comment]
Agreed - this seems mostly to be working now, maybe marginal improvements in the future for slight differences in log absolute value but the effect seems small at this point
