### ISSUE TITLE
absoluteFlux calculation wrong for Ping Pong mechanisms

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASSef#87]
The absoluteFlux equation is calculated as the sum of all transition steps in the enzyme mechanism. However, in the pint pong mechanism there are two transition steps that are sequential, and not parallel.
To fix this, just check for the enzyme mechanism -> if ping pong, take only one of the transition steps.
How to check for enzyme mechanism, 
   option 1: add the mechanism as an argument for the function that calculates the absoluteFlux
   option 2: check for "mod" in the enzyme species of the transition steps? however, that limits the way to define ping pong mechanisms and can easily lead to errors.

**Comment by dczielinski** [comment]
another solution would be to allow the user to provide a set of transition steps, to use in place of automatically calculated steps, with a warning that they should do this for ping pong

**Comment by martamatos** [comment]
This has been fixed in commit 10e4e34a314fa9d894319a7f2fff574c5a9fe50d
